export const metadata = {
  title: '자주하시는 질문',
  description: 'Generated by 자주하시는 질문',
}

export default function RootLayout({ children }) {
  return (
    <>
      <h2>FAQ layout</h2>
      <div>{children}</div>
    </>
  )
}
