export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
      <h2>about layout</h2>
      <div>{children}</div>
    </>
  )
}
